### ISSUE TITLE
Broken links if user select criteria from the main page

### ISSUE THREAD

**Issue by 4PixelsDev** [brettohland/fuckingformatstyle#12]
Steps to reproduce the issue:
- Open the main `https://fuckingformatstyle.com/` page
- Select I have a Number
- And it's actually a percentage
- Grouping

Clicking on the link page 404 opens and the link navigates to `https://fuckingformatstyle.com/number-styles/#percent-grouping`

If you return back to the main page
- from the left menu open Percent Style
- And then from the section Available Properties select `Grouping`

The page opens regularly and the link navigates to `https://fuckingformatstyle.com/numeric-styles/#percent-grouping` will open.

The problem with links from the main page is that they lead to `/number-styles` instead `/numeric-styles`

All links from the main page should be double-checked.

**Comment by 4PixelsDev** [comment]
Keep up the good work, the site is super helpful :)

**Comment by brettohland** [comment]
@4PixelsDev Thanks so much for catching that, and the kind words. I've pushed up this change.
