### ISSUE TITLE
Suggestion for additional example in formatting for money by locale

### ISSUE THREAD

**Issue by karanj** [brettohland/fuckingformatstyle#15]
Suggestion - local hi or en_IN will show a different thousands separation, since Indian convention is to do comma after 3 and then every 2 figures

so e.g. `Decimal(10000000).formatted(.currency(code: "GBP").locale(Locale(identifier: "hi_IN")))` returns "£1,00,00,000.00" rather than "£10,000,000.00" that you'd expect in en_US

**Comment by brettohland** [comment]
@karanj This is a great suggestion, I'll add this to my next batch of updates to the site.
